import type { DataEntry } from '@/types/data';
import type { Variable } from '@/types/variable';
import { createFieldTypeInstance } from '@/types/fields';

export const sampleDataEntries: Record<string, DataEntry[]> = {
  character: [
    {
      id: 'lex',
      typeId: 'character',
      values: {
        name: 'レックス',
        description: '世界を旅する冒険者',
        face_graphic: 'face_lex',
        walk_graphic: 'walk_lex',
        job: 'traveler',
        initial_level: 1,
        base_stats: { hp: 400, mp: 60, atk: 30, def: 25, matk: 15, mdef: 15, spd: 30, luk: 20 },
        element_resistance: [],
        status_resistance: [],
        initial_equipment: 'iron_sword',
      },
    },
    {
      id: 'ian',
      typeId: 'character',
      values: {
        name: 'イアン',
        description: '正義を貫く騎士',
        face_graphic: 'face_ian',
        walk_graphic: 'walk_ian',
        job: 'warrior',
        initial_level: 1,
        base_stats: { hp: 500, mp: 30, atk: 45, def: 40, matk: 5, mdef: 20, spd: 20, luk: 10 },
        element_resistance: [],
        status_resistance: [],
        initial_equipment: 'iron_sword',
      },
    },
    {
      id: 'alice',
      typeId: 'character',
      values: {
        name: 'アリス',
        description: '才能溢れる魔法使い',
        face_graphic: 'face_alice',
        walk_graphic: 'walk_alice',
        job: 'mage',
        initial_level: 1,
        base_stats: { hp: 280, mp: 200, atk: 10, def: 12, matk: 50, mdef: 40, spd: 22, luk: 15 },
        element_resistance: [],
        status_resistance: [],
        initial_equipment: 'magic_staff',
      },
    },
    {
      id: 'marguerite',
      typeId: 'character',
      values: {
        name: 'マルグリット',
        description: '慈悲深い僧侶',
        face_graphic: 'face_margrite',
        walk_graphic: 'walk_marguerite',
        job: 'priest',
        initial_level: 1,
        base_stats: { hp: 350, mp: 150, atk: 15, def: 20, matk: 35, mdef: 45, spd: 18, luk: 25 },
        element_resistance: [],
        status_resistance: [],
        initial_equipment: '',
      },
    },
  ],
  item: [
    {
      id: 'potion_hp',
      typeId: 'item',
      values: {
        name: 'HPポーション',
        description: 'HPを50回復する',
        icon: '',
        item_type: 'consumable',
        price: 100,
        effects: [{ effect_type: 'heal', value: 50 }],
        target: 'single_ally',
        usable_scene: 'both',
      },
    },
    {
      id: 'potion_mp',
      typeId: 'item',
      values: {
        name: 'MPポーション',
        description: 'MPを30回復する',
        icon: '',
        item_type: 'consumable',
        price: 150,
        effects: [{ effect_type: 'heal_mp', value: 30 }],
        target: 'single_ally',
        usable_scene: 'both',
      },
    },
    {
      id: 'antidote',
      typeId: 'item',
      values: {
        name: '解毒草',
        description: '毒状態を治す',
        icon: '',
        item_type: 'consumable',
        price: 50,
        effects: [{ effect_type: 'remove_status', status_id: 'poison' }],
        target: 'single_ally',
        usable_scene: 'both',
        use_se: '',
      },
    },
    {
      id: 'iron_sword',
      typeId: 'item',
      values: {
        name: '鉄の剣',
        description: '基本的な剣',
        icon: '',
        item_type: 'weapon',
        price: 300,
        equip_slot: 'weapon',
        status_bonus: { atk: 15 },
      },
    },
    {
      id: 'magic_staff',
      typeId: 'item',
      values: {
        name: '魔法の杖',
        description: '魔力を高める杖',
        icon: '',
        item_type: 'weapon',
        price: 500,
        equip_slot: 'weapon',
        status_bonus: { mp: 30, atk: 5, matk: 25, mdef: 10 },
      },
    },
    {
      id: 'iron_shield',
      typeId: 'item',
      values: {
        name: '鉄の盾',
        description: '基本的な盾',
        icon: '',
        item_type: 'armor',
        price: 200,
        equip_slot: 'shield',
        status_bonus: { def: 12, mdef: 5, spd: -2 },
      },
    },
    {
      id: 'leather_hat',
      typeId: 'item',
      values: {
        name: '革の帽子',
        description: '軽い帽子',
        icon: '',
        item_type: 'armor',
        price: 80,
        equip_slot: 'head',
        status_bonus: { def: 5, mdef: 3 },
      },
    },
    {
      id: 'leather_armor',
      typeId: 'item',
      values: {
        name: '革の鎧',
        description: '軽くて丈夫な鎧',
        icon: '',
        item_type: 'armor',
        price: 350,
        equip_slot: 'body',
        status_bonus: { def: 18, mdef: 8, spd: -1 },
      },
    },
    {
      id: 'traveler_clothes',
      typeId: 'item',
      values: {
        name: '旅人の服',
        description: '動きやすい服',
        icon: '',
        item_type: 'armor',
        price: 150,
        equip_slot: 'body',
        status_bonus: { def: 8, mdef: 5, spd: 3, luk: 2 },
      },
    },
    {
      id: 'power_ring',
      typeId: 'item',
      values: {
        name: '力の指輪',
        description: '攻撃力を高める指輪',
        icon: '',
        item_type: 'accessory',
        price: 500,
        equip_slot: 'accessory',
        status_bonus: { atk: 10 },
      },
    },
  ],
  skill: [
    {
      id: 'fire_ball',
      typeId: 'skill',
      values: {
        name: 'ファイアボール',
        description: '炎の魔法で敵単体にダメージ',
        icon: '',
        skill_type: 'magical',
        mp_cost: 10,
        target_scope: 'single',
        target_side: 'enemy',
        battle_result: {
          damage: 80,
          hit_rate: 95,
          crit_rate: 5,
          crit_multiplier: 1.5,
          formula: 'matk * 2 - mdef',
        },
        effects: [{ effect_type: 'damage', target: 'single_enemy', value: 80, duration: 0 }],
        element: 'fire',
        status_effects: [],
        usable_scene: 'battle',
        visual_effect: {
          imageId: 'effect_fire',
          frameWidth: 120,
          frameHeight: 120,
          frameCount: 8,
          intervalMs: 80,
        },
        se: '',
      },
    },
    {
      id: 'heal',
      typeId: 'skill',
      values: {
        name: 'ヒール',
        description: '味方一人のHPを80回復する',
        icon: '',
        skill_type: 'magical',
        mp_cost: 8,
        target_scope: 'single',
        target_side: 'ally',
        battle_result: {},
        effects: [{ effect_type: 'heal', target: 'single_ally', value: 80, duration: 0 }],
        element: '',
        status_effects: [],
        usable_scene: 'both',
        visual_effect: {
          imageId: 'effect_heal',
          frameWidth: 120,
          frameHeight: 120,
          frameCount: 8,
          intervalMs: 80,
        },
        se: '',
      },
    },
    {
      id: 'heal_all',
      typeId: 'skill',
      values: {
        name: 'ヒールオール',
        description: '味方全員のHPを50回復する',
        icon: '',
        skill_type: 'magical',
        mp_cost: 20,
        target_scope: 'all',
        target_side: 'ally',
        battle_result: {},
        effects: [{ effect_type: 'heal', target: 'all_allies', value: 50, duration: 0 }],
        element: '',
        status_effects: [],
        usable_scene: 'both',
        visual_effect: {
          imageId: 'effect_heal',
          frameWidth: 120,
          frameHeight: 120,
          frameCount: 8,
          intervalMs: 80,
        },
        se: '',
      },
    },
    {
      id: 'power_up',
      typeId: 'skill',
      values: {
        name: 'パワーアップ',
        description: '自分の攻撃力を10上げる',
        icon: '',
        skill_type: 'special',
        mp_cost: 5,
        target_scope: 'single',
        target_side: 'self',
        battle_result: {},
        effects: [{ effect_type: 'add_status', status_id: 'atk_up' }],
        element: '',
        status_effects: [],
        usable_scene: 'battle',
        visual_effect: {
          imageId: 'effect_up',
          frameWidth: 120,
          frameHeight: 120,
          frameCount: 10,
          intervalMs: 80,
        },
        se: '',
      },
    },
    {
      id: 'ice_lance',
      typeId: 'skill',
      values: {
        name: 'アイスランス',
        description: '氷の槍で敵単体にダメージ',
        icon: '',
        skill_type: 'magical',
        mp_cost: 12,
        target_scope: 'single',
        target_side: 'enemy',
        battle_result: { damage: 90, hit_rate: 90, crit_rate: 10, crit_multiplier: 1.5 },
        effects: [{ effect_type: 'damage', target: 'single_enemy', value: 90, duration: 0 }],
        element: 'ice',
        status_effects: [],
        usable_scene: 'battle',
        visual_effect: {
          imageId: 'effect_ice',
          frameWidth: 120,
          frameHeight: 120,
          frameCount: 8,
          intervalMs: 80,
        },
        se: '',
      },
    },
    {
      id: 'thunder_bolt',
      typeId: 'skill',
      values: {
        name: 'サンダーボルト',
        description: '雷を落とし敵全体にダメージ',
        icon: '',
        skill_type: 'magical',
        mp_cost: 18,
        target_scope: 'all',
        target_side: 'enemy',
        battle_result: { damage: 60, hit_rate: 85, crit_rate: 5, crit_multiplier: 1.5 },
        effects: [{ effect_type: 'damage', target: 'all_enemies', value: 60, duration: 0 }],
        element: 'thunder',
        status_effects: [],
        usable_scene: 'battle',
        visual_effect: {
          imageId: 'effect_thunder',
          frameWidth: 120,
          frameHeight: 120,
          frameCount: 8,
          intervalMs: 80,
        },
        se: '',
      },
    },
    {
      id: 'poison_mist',
      typeId: 'skill',
      values: {
        name: '毒霧',
        description: '敵全体を毒状態にする',
        icon: '',
        skill_type: 'magical',
        mp_cost: 8,
        target_scope: 'all',
        target_side: 'enemy',
        battle_result: {},
        effects: [{ effect_type: 'add_status', status_id: 'poison' }],
        element: '',
        status_effects: [],
        usable_scene: 'battle',
        visual_effect: {
          imageId: 'effect_poison',
          frameWidth: 120,
          frameHeight: 120,
          frameCount: 8,
          intervalMs: 80,
        },
        se: '',
      },
    },
    {
      id: 'defense_up',
      typeId: 'skill',
      values: {
        name: 'プロテクト',
        description: '味方一人の防御力を上げる',
        icon: '',
        skill_type: 'magical',
        mp_cost: 6,
        target_scope: 'single',
        target_side: 'ally',
        battle_result: {},
        effects: [{ effect_type: 'add_status', status_id: 'def_up' }],
        element: '',
        status_effects: [],
        usable_scene: 'battle',
        visual_effect: {
          imageId: 'effect_up',
          frameWidth: 120,
          frameHeight: 120,
          frameCount: 10,
          intervalMs: 80,
        },
        se: '',
      },
    },
    {
      id: 'fire_storm',
      typeId: 'skill',
      values: {
        name: 'ファイアストーム',
        description: '炎の嵐で敵全体に大ダメージ',
        icon: '',
        skill_type: 'magical',
        mp_cost: 30,
        target_scope: 'all',
        target_side: 'enemy',
        battle_result: { damage: 120, hit_rate: 90, crit_rate: 8, crit_multiplier: 2.0 },
        effects: [{ effect_type: 'damage', target: 'all_enemies', value: 120, duration: 0 }],
        element: 'fire',
        status_effects: [],
        usable_scene: 'battle',
        visual_effect: {
          imageId: 'effect_firebomb',
          frameWidth: 120,
          frameHeight: 120,
          frameCount: 7,
          intervalMs: 80,
        },
        se: '',
      },
    },
  ],
  element: [
    {
      id: 'fire',
      typeId: 'element',
      values: { name: '炎', description: '炎属性', icon: '', color: '#ff4444' },
    },
    {
      id: 'ice',
      typeId: 'element',
      values: { name: '氷', description: '氷属性', icon: '', color: '#4488ff' },
    },
    {
      id: 'thunder',
      typeId: 'element',
      values: { name: '雷', description: '雷属性', icon: '', color: '#ffdd44' },
    },
    {
      id: 'earth',
      typeId: 'element',
      values: { name: '地', description: '地属性', icon: '', color: '#88aa44' },
    },
    {
      id: 'wind',
      typeId: 'element',
      values: { name: '風', description: '風属性', icon: '', color: '#66ccaa' },
    },
    {
      id: 'light',
      typeId: 'element',
      values: { name: '光', description: '光属性', icon: '', color: '#ffffaa' },
    },
    {
      id: 'dark',
      typeId: 'element',
      values: { name: '闇', description: '闇属性', icon: '', color: '#8844aa' },
    },
  ],
  status: [
    // 異常状態
    {
      id: 'poison',
      typeId: 'status',
      values: {
        name: '毒',
        description: '毎ターンHPが減少する',
        icon: '',
        effect_type: 'damage_over_time',
        effect_value: 10,
        duration: 5,
        cancel_condition: 'turn_end',
        priority: 50,
      },
    },
    {
      id: 'paralysis',
      typeId: 'status',
      values: {
        name: '麻痺',
        description: '行動不能になることがある',
        icon: '',
        effect_type: 'disable',
        duration: 3,
        cancel_condition: 'turn_end',
        priority: 60,
      },
    },
    {
      id: 'sleep',
      typeId: 'status',
      values: {
        name: '睡眠',
        description: '行動不能。攻撃を受けると解除',
        icon: '',
        effect_type: 'disable',
        duration: 3,
        cancel_condition: 'damage',
        priority: 70,
      },
    },
    {
      id: 'silence',
      typeId: 'status',
      values: {
        name: '沈黙',
        description: '魔法が使えなくなる',
        icon: '',
        effect_type: 'other',
        effect_value: 0,
        duration: 4,
        cancel_condition: 'turn_end',
        priority: 40,
      },
    },
    {
      id: 'blind',
      typeId: 'status',
      values: {
        name: '暗闇',
        description: '命中率が低下する',
        icon: '',
        effect_type: 'other',
        effect_value: 0,
        duration: 4,
        cancel_condition: 'turn_end',
        priority: 30,
      },
    },
    {
      id: 'confusion',
      typeId: 'status',
      values: {
        name: '混乱',
        description: '敵味方ランダムに攻撃する',
        icon: '',
        effect_type: 'confusion',
        duration: 3,
        cancel_condition: 'damage',
        priority: 65,
      },
    },
    // ステータス変動
    {
      id: 'atk_up',
      typeId: 'status',
      values: {
        name: 'ATK上昇',
        description: '攻撃力が上がる',
        icon: '',
        effect_type: 'stat_change',
        stat_modifier: { atk: 15 },
        duration: 5,
        cancel_condition: 'turn_end',
        priority: 20,
      },
    },
    {
      id: 'def_up',
      typeId: 'status',
      values: {
        name: 'DEF上昇',
        description: '防御力が上がる',
        icon: '',
        effect_type: 'stat_change',
        stat_modifier: { def: 15 },
        duration: 5,
        cancel_condition: 'turn_end',
        priority: 20,
      },
    },
    {
      id: 'atk_down',
      typeId: 'status',
      values: {
        name: 'ATK低下',
        description: '攻撃力が下がる',
        icon: '',
        effect_type: 'stat_change',
        stat_modifier: { atk: -10 },
        duration: 5,
        cancel_condition: 'turn_end',
        priority: 20,
      },
    },
    {
      id: 'def_down',
      typeId: 'status',
      values: {
        name: 'DEF低下',
        description: '防御力が下がる',
        icon: '',
        effect_type: 'stat_change',
        stat_modifier: { def: -10 },
        duration: 5,
        cancel_condition: 'turn_end',
        priority: 20,
      },
    },
    {
      id: 'spd_up',
      typeId: 'status',
      values: {
        name: 'SPD上昇',
        description: '素早さが上がる',
        icon: '',
        effect_type: 'stat_change',
        stat_modifier: { spd: 10 },
        duration: 5,
        cancel_condition: 'turn_end',
        priority: 20,
      },
    },
  ],
  enemy: [
    {
      id: 'slime',
      typeId: 'enemy',
      values: {
        name: 'スライム',
        description: '最も弱いモンスター',
        graphic: 'enemy_slime',
        base_stats: { hp: 30, mp: 5, atk: 8, def: 5, matk: 3, mdef: 3, spd: 4, luk: 2 },
        exp: 5,
        gold: 10,
        drop_items: [{ item: 'potion_hp', rate: 30 }],
        element_resistance: [],
        status_resistance: [],
        action_patterns: [{ skill: '', condition: 'always', priority: 5 }],
      },
    },
    {
      id: 'ox',
      typeId: 'enemy',
      values: {
        name: '暴れ牛',
        description: '突進してくる獣',
        graphic: 'enemy_ox',
        base_stats: { hp: 70, mp: 0, atk: 25, def: 15, matk: 0, mdef: 8, spd: 12, luk: 3 },
        exp: 18,
        gold: 30,
        drop_items: [],
        element_resistance: [],
        status_resistance: [],
        action_patterns: [{ skill: '', condition: 'always', priority: 5 }],
      },
    },
    {
      id: 'golem',
      typeId: 'enemy',
      values: {
        name: 'ゴーレム',
        description: '岩でできた巨人',
        graphic: 'enemy_golem',
        base_stats: { hp: 200, mp: 0, atk: 35, def: 40, matk: 5, mdef: 20, spd: 3, luk: 1 },
        exp: 50,
        gold: 80,
        drop_items: [{ item: 'iron_shield', rate: 10 }],
        element_resistance: [],
        status_resistance: ['poison', 'sleep', 'silence'],
        action_patterns: [{ skill: '', condition: 'always', priority: 5 }],
      },
    },
    {
      id: 'wyvern',
      typeId: 'enemy',
      values: {
        name: 'ワイバーン',
        description: '空を飛ぶ翼竜',
        graphic: 'enemy_wyvern',
        base_stats: { hp: 150, mp: 30, atk: 30, def: 20, matk: 25, mdef: 18, spd: 22, luk: 8 },
        exp: 40,
        gold: 60,
        drop_items: [{ item: 'antidote', rate: 15 }],
        element_resistance: [],
        status_resistance: [],
        action_patterns: [
          { skill: 'fire_ball', condition: 'always', priority: 6 },
          { skill: '', condition: 'always', priority: 4 },
        ],
      },
    },
    {
      id: 'dragon',
      typeId: 'enemy',
      values: {
        name: 'ドラゴン',
        description: '火を吹く巨大な竜',
        graphic: 'enemy_fire_dragon',
        base_stats: { hp: 500, mp: 100, atk: 60, def: 45, matk: 55, mdef: 40, spd: 15, luk: 10 },
        exp: 200,
        gold: 500,
        drop_items: [{ item: 'power_ring', rate: 15 }],
        element_resistance: ['fire'],
        status_resistance: ['poison', 'sleep'],
        action_patterns: [
          { skill: 'fire_ball', condition: 'always', priority: 7 },
          { skill: '', condition: 'always', priority: 3 },
          { skill: '', condition: 'hp_low', priority: 9 },
        ],
      },
    },
  ],
  enemy_group: [
    {
      id: 'field_slime',
      typeId: 'enemy_group',
      values: {
        name: 'スライムの群れ',
        location: '草原',
        members: [{ enemy: 'slime', count: 3 }],
        battle_bgm: '',
        background: '',
      },
    },
    {
      id: 'field_ox',
      typeId: 'enemy_group',
      values: {
        name: '暴れ牛の群れ',
        location: '草原',
        members: [
          { enemy: 'ox', count: 2 },
          { enemy: 'slime', count: 1 },
        ],
        battle_bgm: '',
        background: '',
      },
    },
    {
      id: 'cave_golem',
      typeId: 'enemy_group',
      values: {
        name: 'ゴーレムの間',
        location: '洞窟',
        members: [{ enemy: 'golem', count: 1 }],
        battle_bgm: '',
        background: '',
      },
    },
    {
      id: 'sky_wyvern',
      typeId: 'enemy_group',
      values: {
        name: 'ワイバーンの巣',
        location: '山岳',
        members: [{ enemy: 'wyvern', count: 2 }],
        battle_bgm: '',
        background: '',
      },
    },
    {
      id: 'boss_dragon',
      typeId: 'enemy_group',
      values: {
        name: 'ドラゴンの洞窟',
        location: '火山',
        members: [
          { enemy: 'dragon', count: 1 },
          { enemy: 'wyvern', count: 1 },
        ],
        battle_bgm: '',
        background: '',
      },
    },
  ],
  job: [
    {
      id: 'warrior',
      typeId: 'job',
      values: {
        name: '戦士',
        description: '近接戦闘に長けた職業',
        icon: '',
        growth_rates: { hp: 120, mp: 50, atk: 110, def: 100, matk: 40, mdef: 60, spd: 80, luk: 70 },
        learn_skills: [{ level: 1, skill: 'power_up' }],
        equippable_types: [],
      },
    },
    {
      id: 'mage',
      typeId: 'job',
      values: {
        name: '魔法使い',
        description: '魔法攻撃に長けた職業',
        icon: '',
        growth_rates: { hp: 70, mp: 130, atk: 30, def: 50, matk: 120, mdef: 100, spd: 60, luk: 80 },
        learn_skills: [
          { level: 1, skill: 'fire_ball' },
          { level: 3, skill: 'ice_lance' },
          { level: 5, skill: 'heal' },
          { level: 8, skill: 'thunder_bolt' },
          { level: 12, skill: 'fire_storm' },
        ],
        equippable_types: [],
      },
    },
    {
      id: 'traveler',
      typeId: 'job',
      values: {
        name: '旅人',
        description: 'バランスの良い冒険者',
        icon: '',
        growth_rates: { hp: 90, mp: 70, atk: 80, def: 75, matk: 60, mdef: 60, spd: 100, luk: 90 },
        learn_skills: [
          { level: 1, skill: 'heal' },
          { level: 4, skill: 'power_up' },
        ],
        equippable_types: [],
      },
    },
    {
      id: 'priest',
      typeId: 'job',
      values: {
        name: '僧侶',
        description: '回復と支援に長けた職業',
        icon: '',
        growth_rates: { hp: 85, mp: 120, atk: 40, def: 65, matk: 90, mdef: 110, spd: 55, luk: 95 },
        learn_skills: [
          { level: 1, skill: 'heal' },
          { level: 3, skill: 'defense_up' },
          { level: 5, skill: 'heal_all' },
          { level: 10, skill: 'poison_mist' },
        ],
        equippable_types: [],
      },
    },
  ],
};

// ── 変数 ──

export function createTestVariables(): Variable[] {
  const numberType = createFieldTypeInstance('number')!;
  const classType = createFieldTypeInstance('class')!;
  Object.assign(classType, { classId: 'class_status' });
  return [
    {
      id: 'var_gold',
      name: 'gold',
      fieldType: numberType,
      isArray: false,
      initialValue: 1000,
      description: '所持金',
    },
    {
      id: 'var_leader_stats',
      name: 'leader_stats',
      fieldType: Object.assign(createFieldTypeInstance('class')!, { classId: 'class_status' }),
      isArray: false,
      initialValue: { hp: 500, mp: 80, atk: 45, def: 30, matk: 15, mdef: 20, spd: 25, luk: 10 },
      description: 'パーティリーダーの現在ステータス（クラス型変数テスト）',
    },
    {
      id: 'var_inventory',
      name: 'inventory',
      fieldType: Object.assign(createFieldTypeInstance('class')!, {
        classId: 'class_inventory_item',
      }),
      isArray: true,
      initialValue: [
        { itemId: 'potion_hp', count: 5 },
        { itemId: 'potion_mp', count: 3 },
        { itemId: 'antidote', count: 2 },
        { itemId: 'iron_sword', count: 1 },
        { itemId: 'magic_staff', count: 1 },
        { itemId: 'iron_shield', count: 2 },
        { itemId: 'leather_hat', count: 1 },
        { itemId: 'leather_armor', count: 2 },
        { itemId: 'traveler_clothes', count: 1 },
        { itemId: 'power_ring', count: 2 },
      ],
      description: '所持アイテム（{itemId, count} 形式）',
    },
    {
      id: 'var_party_init',
      name: 'party_init',
      fieldType: Object.assign(createFieldTypeInstance('class')!, { classId: 'class_party_init' }),
      isArray: true,
      initialValue: [
        { characterId: 'lex', level: 10 },
        { characterId: 'ian', level: 12 },
        { characterId: 'alice', level: 8 },
        { characterId: 'marguerite', level: 9 },
      ],
      description: '初期パーティ定義（ゲーム開始時に init_party で party に展開）',
    },
    {
      id: 'var_party',
      name: 'party',
      fieldType: Object.assign(createFieldTypeInstance('class')!, {
        classId: 'class_party_member',
      }),
      isArray: true,
      initialValue: [],
      description: 'パーティメンバー配列（init_party スクリプトで party_init から生成）',
    },
  ];
}
