import type { DataEntry } from '@/types/data';
import type { Variable } from '@/types/variable';
import { createFieldTypeInstance } from '@/types/fields';

export const sampleDataEntries: Record<string, DataEntry[]> = {
  character: [
    {
      id: 'lex',
      typeId: 'character',
      values: {
        name: 'レックス',
        description: '世界を旅する冒険者',
        face_graphic: 'face_lex',
        walk_graphic: 'walk_lex',
        job: 'traveler',
        initial_level: 1,
        base_stats: { hp: 400, mp: 60, atk: 30, def: 25, matk: 15, mdef: 15, spd: 30, luk: 20 },
        element_resistance: [],
        status_resistance: [],
        initial_equipment: 'iron_sword',
      },
    },
    {
      id: 'ian',
      typeId: 'character',
      values: {
        name: 'イアン',
        description: '正義を貫く騎士',
        face_graphic: 'face_ian',
        walk_graphic: 'walk_ian',
        job: 'warrior',
        initial_level: 1,
        base_stats: { hp: 500, mp: 30, atk: 45, def: 40, matk: 5, mdef: 20, spd: 20, luk: 10 },
        element_resistance: [],
        status_resistance: [],
        initial_equipment: 'iron_sword',
      },
    },
    {
      id: 'alice',
      typeId: 'character',
      values: {
        name: 'アリス',
        description: '才能溢れる魔法使い',
        face_graphic: 'face_alice',
        walk_graphic: 'walk_alice',
        job: 'mage',
        initial_level: 1,
        base_stats: { hp: 280, mp: 200, atk: 10, def: 12, matk: 50, mdef: 40, spd: 22, luk: 15 },
        element_resistance: [],
        status_resistance: [],
        initial_equipment: 'magic_staff',
      },
    },
    {
      id: 'marguerite',
      typeId: 'character',
      values: {
        name: 'マルグリット',
        description: '慈悲深い僧侶',
        face_graphic: 'face_margrite',
        walk_graphic: 'walk_marguerite',
        job: 'priest',
        initial_level: 1,
        base_stats: { hp: 350, mp: 150, atk: 15, def: 20, matk: 35, mdef: 45, spd: 18, luk: 25 },
        element_resistance: [],
        status_resistance: [],
        initial_equipment: '',
      },
    },
  ],
  item: [
    {
      id: 'potion_hp',
      typeId: 'item',
      values: {
        name: 'HPポーション',
        description: 'HPを50回復する',
        icon: '',
        item_type: 'consumable',
        price: 100,
        effects: [{ effect_type: 'heal', target: 'single_ally', value: 50, duration: 0 }],
        target: 'single_ally',
        equip_slot: 'none',
        status_bonus: {},
        element_bonus: '',
        status_resistance: [],
        usable_scene: 'both',
        use_se: '',
      },
    },
    {
      id: 'potion_mp',
      typeId: 'item',
      values: {
        name: 'MPポーション',
        description: 'MPを30回復する',
        icon: '',
        item_type: 'consumable',
        price: 150,
        effects: [{ effect_type: 'heal_mp', target: 'single_ally', value: 30, duration: 0 }],
        target: 'single_ally',
        equip_slot: 'none',
        status_bonus: {},
        element_bonus: '',
        status_resistance: [],
        usable_scene: 'both',
        use_se: '',
      },
    },
    {
      id: 'antidote',
      typeId: 'item',
      values: {
        name: '解毒草',
        description: '毒状態を治す',
        icon: '',
        item_type: 'consumable',
        price: 50,
        effects: [{ effect_type: 'heal', target: 'single_ally', value: 0, duration: 0 }],
        target: 'single_ally',
        equip_slot: 'none',
        status_bonus: {},
        element_bonus: '',
        status_resistance: [],
        usable_scene: 'both',
        use_se: '',
      },
    },
    {
      id: 'iron_sword',
      typeId: 'item',
      values: {
        name: '鉄の剣',
        description: '基本的な剣',
        icon: '',
        item_type: 'weapon',
        price: 300,
        effects: [],
        target: 'single_enemy',
        equip_slot: 'weapon',
        status_bonus: { hp: 0, mp: 0, atk: 15, def: 0, matk: 0, mdef: 0, spd: 0, luk: 0 },
        element_bonus: '',
        status_resistance: [],
        usable_scene: 'none',
        use_se: '',
      },
    },
    {
      id: 'magic_staff',
      typeId: 'item',
      values: {
        name: '魔法の杖',
        description: '魔力を高める杖',
        icon: '',
        item_type: 'weapon',
        price: 500,
        effects: [],
        target: 'single_enemy',
        equip_slot: 'weapon',
        status_bonus: { hp: 0, mp: 30, atk: 5, def: 0, matk: 25, mdef: 10, spd: 0, luk: 0 },
        element_bonus: '',
        status_resistance: [],
        usable_scene: 'none',
        use_se: '',
      },
    },
    {
      id: 'iron_shield',
      typeId: 'item',
      values: {
        name: '鉄の盾',
        description: '基本的な盾',
        icon: '',
        item_type: 'armor',
        price: 200,
        effects: [],
        target: 'single_ally',
        equip_slot: 'shield',
        status_bonus: { hp: 0, mp: 0, atk: 0, def: 12, matk: 0, mdef: 5, spd: -2, luk: 0 },
        element_bonus: '',
        status_resistance: [],
        usable_scene: 'none',
        use_se: '',
      },
    },
    {
      id: 'leather_hat',
      typeId: 'item',
      values: {
        name: '革の帽子',
        description: '軽い帽子',
        icon: '',
        item_type: 'armor',
        price: 80,
        effects: [],
        target: 'single_ally',
        equip_slot: 'head',
        status_bonus: { hp: 0, mp: 0, atk: 0, def: 5, matk: 0, mdef: 3, spd: 0, luk: 0 },
        element_bonus: '',
        status_resistance: [],
        usable_scene: 'none',
        use_se: '',
      },
    },
    {
      id: 'leather_armor',
      typeId: 'item',
      values: {
        name: '革の鎧',
        description: '軽くて丈夫な鎧',
        icon: '',
        item_type: 'armor',
        price: 350,
        effects: [],
        target: 'single_ally',
        equip_slot: 'body',
        status_bonus: { hp: 0, mp: 0, atk: 0, def: 18, matk: 0, mdef: 8, spd: -1, luk: 0 },
        element_bonus: '',
        status_resistance: [],
        usable_scene: 'none',
        use_se: '',
      },
    },
    {
      id: 'traveler_clothes',
      typeId: 'item',
      values: {
        name: '旅人の服',
        description: '動きやすい服',
        icon: '',
        item_type: 'armor',
        price: 150,
        effects: [],
        target: 'single_ally',
        equip_slot: 'body',
        status_bonus: { hp: 0, mp: 0, atk: 0, def: 8, matk: 0, mdef: 5, spd: 3, luk: 2 },
        element_bonus: '',
        status_resistance: [],
        usable_scene: 'none',
        use_se: '',
      },
    },
    {
      id: 'power_ring',
      typeId: 'item',
      values: {
        name: '力の指輪',
        description: '攻撃力を高める指輪',
        icon: '',
        item_type: 'accessory',
        price: 500,
        effects: [],
        target: 'single_ally',
        equip_slot: 'accessory',
        status_bonus: { hp: 0, mp: 0, atk: 10, def: 0, matk: 0, mdef: 0, spd: 0, luk: 0 },
        element_bonus: '',
        status_resistance: [],
        usable_scene: 'none',
        use_se: '',
      },
    },
  ],
  skill: [
    {
      id: 'fire_ball',
      typeId: 'skill',
      values: {
        name: 'ファイアボール',
        description: '炎の魔法で敵単体にダメージ',
        icon: '',
        skill_type: 'magical',
        mp_cost: 10,
        target_scope: 'single',
        target_side: 'enemy',
        battle_result: { damage: 80, hit_rate: 95, crit_rate: 5, crit_multiplier: 1.5, formula: 'matk * 2 - mdef' },
        effects: [{ effect_type: 'damage', target: 'single_enemy', value: 80, duration: 0 }],
        element: 'fire',
        status_effects: [],
        usable_scene: 'battle',
        se: '',
      },
    },
    {
      id: 'heal',
      typeId: 'skill',
      values: {
        name: 'ヒール',
        description: '味方一人のHPを80回復する',
        icon: '',
        skill_type: 'magical',
        mp_cost: 8,
        target_scope: 'single',
        target_side: 'ally',
        battle_result: {},
        effects: [{ effect_type: 'heal', target: 'single_ally', value: 80, duration: 0 }],
        element: '',
        status_effects: [],
        usable_scene: 'both',
        se: '',
      },
    },
    {
      id: 'heal_all',
      typeId: 'skill',
      values: {
        name: 'ヒールオール',
        description: '味方全員のHPを50回復する',
        icon: '',
        skill_type: 'magical',
        mp_cost: 20,
        target_scope: 'all',
        target_side: 'ally',
        battle_result: {},
        effects: [{ effect_type: 'heal', target: 'all_allies', value: 50, duration: 0 }],
        element: '',
        status_effects: [],
        usable_scene: 'both',
        se: '',
      },
    },
    {
      id: 'power_up',
      typeId: 'skill',
      values: {
        name: 'パワーアップ',
        description: '自分の攻撃力を10上げる',
        icon: '',
        skill_type: 'special',
        mp_cost: 5,
        target_scope: 'single',
        target_side: 'self',
        battle_result: {},
        effects: [{ effect_type: 'buff', target: 'self', value: 10, duration: 3 }],
        element: '',
        status_effects: [],
        usable_scene: 'battle',
        se: '',
      },
    },
  ],
  element: [
    { id: 'fire', typeId: 'element', values: { name: '炎', description: '炎属性', icon: '', color: '#ff4444' } },
    { id: 'ice', typeId: 'element', values: { name: '氷', description: '氷属性', icon: '', color: '#4488ff' } },
  ],
  job: [
    {
      id: 'warrior',
      typeId: 'job',
      values: {
        name: '戦士',
        description: '近接戦闘に長けた職業',
        icon: '',
        growth_rates: { hp: 120, mp: 50, atk: 110, def: 100, matk: 40, mdef: 60, spd: 80, luk: 70 },
        learn_skills: [{ level: 1, skill: 'power_up' }],
        equippable_types: [],
      },
    },
    {
      id: 'mage',
      typeId: 'job',
      values: {
        name: '魔法使い',
        description: '魔法攻撃に長けた職業',
        icon: '',
        growth_rates: { hp: 70, mp: 130, atk: 30, def: 50, matk: 120, mdef: 100, spd: 60, luk: 80 },
        learn_skills: [{ level: 1, skill: 'fire_ball' }, { level: 5, skill: 'heal' }],
        equippable_types: [],
      },
    },
    {
      id: 'traveler',
      typeId: 'job',
      values: {
        name: '旅人',
        description: 'バランスの良い冒険者',
        icon: '',
        growth_rates: { hp: 90, mp: 70, atk: 80, def: 75, matk: 60, mdef: 60, spd: 100, luk: 90 },
        learn_skills: [{ level: 1, skill: 'heal' }],
        equippable_types: [],
      },
    },
    {
      id: 'priest',
      typeId: 'job',
      values: {
        name: '僧侶',
        description: '回復と支援に長けた職業',
        icon: '',
        growth_rates: { hp: 85, mp: 120, atk: 40, def: 65, matk: 90, mdef: 110, spd: 55, luk: 95 },
        learn_skills: [{ level: 1, skill: 'heal' }, { level: 5, skill: 'heal_all' }],
        equippable_types: [],
      },
    },
  ],
};

// ── 変数 ──

export function createTestVariables(): Variable[] {
  const numberType = createFieldTypeInstance('number')!;
  const classType = createFieldTypeInstance('class')!;
  Object.assign(classType, { classId: 'class_status' });
  return [
    {
      id: 'var_gold',
      name: 'gold',
      fieldType: numberType,
      isArray: false,
      initialValue: 1000,
      description: '所持金',
    },
    {
      id: 'var_leader_stats',
      name: 'leader_stats',
      fieldType: Object.assign(createFieldTypeInstance('class')!, { classId: 'class_status' }),
      isArray: false,
      initialValue: { hp: 500, mp: 80, atk: 45, def: 30, matk: 15, mdef: 20, spd: 25, luk: 10 },
      description: 'パーティリーダーの現在ステータス（クラス型変数テスト）',
    },
    {
      id: 'var_inventory',
      name: 'inventory',
      fieldType: Object.assign(createFieldTypeInstance('class')!, { classId: 'class_inventory_item' }),
      isArray: true,
      initialValue: [
        { itemId: 'potion_hp', count: 5 },
        { itemId: 'potion_mp', count: 3 },
        { itemId: 'antidote', count: 2 },
        { itemId: 'iron_sword', count: 1 },
        { itemId: 'magic_staff', count: 1 },
        { itemId: 'iron_shield', count: 2 },
        { itemId: 'leather_hat', count: 1 },
        { itemId: 'leather_armor', count: 2 },
        { itemId: 'traveler_clothes', count: 1 },
        { itemId: 'power_ring', count: 2 },
      ],
      description: '所持アイテム（{itemId, count} 形式）',
    },
    {
      id: 'var_party_init',
      name: 'party_init',
      fieldType: Object.assign(createFieldTypeInstance('class')!, { classId: 'class_party_init' }),
      isArray: true,
      initialValue: [
        { characterId: 'lex', level: 10 },
        { characterId: 'ian', level: 12 },
        { characterId: 'alice', level: 8 },
        { characterId: 'marguerite', level: 9 },
      ],
      description: '初期パーティ定義（ゲーム開始時に init_party で party に展開）',
    },
    {
      id: 'var_party',
      name: 'party',
      fieldType: Object.assign(createFieldTypeInstance('class')!, { classId: 'class_party_member' }),
      isArray: true,
      initialValue: [],
      description: 'パーティメンバー配列（init_party スクリプトで party_init から生成）',
    },
  ];
}

