import { registerUIComponent } from './index';
import { ImageComponent } from './components/ImageComponent';
import { TextComponent } from './components/TextComponent';
import { ShapeComponent } from './components/ShapeComponent';
import { LineComponent } from './components/LineComponent';
import { FillMaskComponent } from './components/FillMaskComponent';
import { ColorMaskComponent } from './components/ColorMaskComponent';
import { LayoutGroupComponent } from './components/LayoutGroupComponent';
import { GridLayoutComponent } from './components/GridLayoutComponent';
import { NavigationComponent } from './components/NavigationComponent';
import { NavigationItemComponent } from './components/NavigationItemComponent';
import { NavigationCursorComponent } from './components/NavigationCursorComponent';
import { AnimationComponent } from './components/AnimationComponent';
import { TemplateControllerComponent } from './components/TemplateControllerComponent';
import { RepeaterComponent } from './components/RepeaterComponent';

registerUIComponent('image', ImageComponent);
registerUIComponent('text', TextComponent);
registerUIComponent('shape', ShapeComponent);
registerUIComponent('line', LineComponent);
registerUIComponent('fillMask', FillMaskComponent);
registerUIComponent('colorMask', ColorMaskComponent);
registerUIComponent('layoutGroup', LayoutGroupComponent);
registerUIComponent('gridLayout', GridLayoutComponent);
registerUIComponent('navigation', NavigationComponent);
registerUIComponent('navigationItem', NavigationItemComponent);
registerUIComponent('navigationCursor', NavigationCursorComponent);
registerUIComponent('animation', AnimationComponent);
registerUIComponent('templateController', TemplateControllerComponent);
registerUIComponent('repeater', RepeaterComponent);
